### ISSUE TITLE
Fragen/ToDo's Mock-ups

### ISSUE THREAD

**Issue by nikolockenvitz** [wwi17seb/dhbw-project-frontend#28]
- [x] Modulkataloge hinzufügen
  - [x] es sollte Studiengang und Studienrichtung sein (und nicht Studienrichtung und Spezifikation)
  - [x] der Studiengang ist als Dropdown sinnvoll, aber die Studienrichtung nicht - die will man ja damit anlegen
  - [x] gibt es eine Möglichkeit die Studiengänge irgendwo zu verwalten?
- [x] Modul hinzufügen
  - [x] wie wollt ihr Wahlmodule konkret im Front-End darstellen? eine Definition als Wahlmodul reicht dafür leider nicht - man muss ja irgendwie eine Gruppe aus Wahlmodulen definieren, aus denen z. B. eines ausgewählt werden muss (wir stellen euch gerne zeitnah nochmal unser Datenmodell hierzu vor, das Wahlmodule und Wahlvorlesungen bereits vollständig abbildet)
  - [x] beim Semester sollte man von/bis angeben können, z. B. 3-4
  - [x] wo genau werden die Prüfungsleistungen verwaltet? also wo kann man diese Typen (Klausur, Seminararbeit, ...) ganz allgemein erstellen/bearbeiten/löschen?
  - [x] sollte es nicht eine Möglichkeit geben, um Vorlesungen mit Schwerpunkten zu verknüpfen?
  - [x] ich gehe mal davon aus, dass die untersten drei Felder bei Workload berechnet sind und keine Eingabefelder sind?!
- [x] Dozentenliste - Detail / Dozent hinzufügen
  - [x] wo sieht man, ob ein Dozent extern oder intern ist?
  - [x] wo sieht man bei der Ansicht, wer den Dozenten angelegt hat (Detailansicht)?
  - [x] wir sind vom Back-End davon ausgegangen, dass es einen Kommentar gibt und nicht eine Art Chat-Funktion - wir können das mit Verweis auf eine entsprechende Anforderung gerne anpassen, aber uns ist aktuell keine solche bekannt
  - [x] beim Anlegen eines Dozenten sollte der Studiengangsleiter nicht angegeben werden müssen - man legt das doch immer für sich selbst an?!
- [x] Kontoeinstellungen
  - [x] wozu gibt es mehrere E-Mail-Adressen? wir gehen von einem Nutzernamen aus (in den man natürlich auch seine E-Mail eintragen könnte; es gibt keinen separaten Namen, nur Nutzername/Passwort)
- [x] wie stellt ihr euch die Umsetzung von "Passwort vergessen?" vor? wir könnten uns einen Passwort-Reset durch Administratoren vorstellen
- [x] neuen Kurs hinzufügen
  - [x] wozu dient das Feld "Jahrgang"? Das ist im Kursnamen enthalten und sollte doch eigentlich ersichtlich sein?
  - [x] wo wählt man hier den konkreten Modulkatalog zum Kurs aus? es fehlt hier noch das Jahr
  - [x] beim Anlegen von Kursen müssen die Semester definiert werden (wie viele und Zeitraum)
- [x] Verwaltung weiterer Entitäten
  - [x] wo werden Schwerpunkte / MainFocuses verwaltet?
  - [x] wo werden Prüfungsleistungen / AcademicRecords verwaltet?
- [ ] Weitere Kommentare
